version: "3.0"

services:
  postgres:
    image: postgres:17.5
    restart: "no"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance

volumes:
  postgres_data:
